#!/usr/bin/env python3
"""
gen-skills-readme.py — okhp3-skill-cataloger v1.6.1
OverKill Hill P³ · https://overkillhill.com · https://github.com/OKHP3
=======================================================
Bundled with the okhp3-skill-cataloger Agent Skill.
Canonical source: scripts/gen-skills-readme.py at project root.
Keep both copies in sync when updating.

Two modes of operation:

  CATALOG (default)
    Scans .agents/skills/, generates .agents/skills/README.md.
    Requires the README to exist with marker comments in place.
    Writes .agents/skills/.catalog-meta.json on every successful run.
    $ python3 scripts/gen-skills-readme.py

  FULL INDEX (--full)
    Scans root-level family folders for the distribution surface.
    Writes README.md catalog section (created if not present).
    Writes FAMILY.md inside each discovered family directory.
    Writes the Families table in README.md (requires markers in place).
    Writes .catalog-meta.json at repo root on every successful run.
    Use in distribution repos (skillz). In an application repo it may produce an
    empty distribution index, so prefer catalog mode unless root families exist.
    $ python3 scripts/gen-skills-readme.py --full
    $ python3 scripts/gen-skills-readme.py --full --no-family-md
    $ python3 scripts/gen-skills-readme.py --full --no-absorb-readme

No external dependencies. Python 3.9+ only.

What changed in v1.6.1 vs v1.6.0:
  - Normalize generated catalog output to one final newline.

What changed in v1.7.0 vs v1.6.1:
  - Exclude root skills/ publication mirrors from full distribution indexing.

What changed in v1.6.0 vs v1.5.0:
  - Configured UTF-8 stdout and stderr so warning output remains portable in Windows consoles.

What changed in v1.5.0 vs v1.4.0:
  - Clarified catalog/full-index contracts and safe dry-run/check behavior in the skill docs.
  - Kept generator behavior deterministic; no live benchmark claims are added.

What changed in v1.4.0 vs v1.3.0:
  - FAMILY.md now has a free-form bio section between the title and
    FAMILY_SUMMARY_START. On first creation, this is populated from the
    family's README.md (the heading is stripped). Preserved on re-runs.
  - On first FAMILY.md creation, if a README.md exists in the family
    directory, it is absorbed into the bio section and then deleted.
    Use --no-absorb-readme to skip the deletion.
  - New FAMILIES_TABLE_START/END markers: --full injects an auto-generated
    Families table into root README.md (all family dirs, including 0-skill
    placeholders). Add the markers to README.md to enable this.
  - New: discover_all_families(), build_families_table(), inject_families_table()
  - FAMILIES_TABLE_START, FAMILIES_TABLE_END constants added.

What changed in v1.3.0 vs v1.2.0:
  - --full now also writes FAMILY.md inside each discovered family directory
  - FAMILY.md contains: YAML frontmatter, auto-sourced summary (preserved on
    re-runs if user edits), and an always-regenerated inventory table
  - Summary sourced from first substantive paragraph of family README.md; falls
    back to aggregated child-skill descriptions when README.md is absent
  - --no-family-md flag: skip FAMILY.md generation during --full (opt-out)

What changed in v1.2.0 vs v1.1.0:
  - --full flag: scans root family folders → README.md (distribution surface)
  - --output: override the output file path (both modes)
  - surface field added to .catalog-meta.json
  - Full index mode: README.md auto-created if not present

Usage:
    python3 scripts/gen-skills-readme.py
    python3 scripts/gen-skills-readme.py --skills-dir .agents/skills
    python3 scripts/gen-skills-readme.py --mode library
    python3 scripts/gen-skills-readme.py --check
    python3 scripts/gen-skills-readme.py --json
    python3 scripts/gen-skills-readme.py --dry-run
    python3 scripts/gen-skills-readme.py --quiet
    python3 scripts/gen-skills-readme.py --full
    python3 scripts/gen-skills-readme.py --full --dry-run
    python3 scripts/gen-skills-readme.py --full --no-family-md
    python3 scripts/gen-skills-readme.py --full --no-absorb-readme
    python3 scripts/gen-skills-readme.py --full --output my-catalog.md
"""

import argparse
import json
import re
import sys
from datetime import datetime, timezone
from pathlib import Path

# Windows consoles can default to cp1252, while catalog warnings intentionally
# include Unicode status glyphs. Keep stdout/stderr portable for interactive use.
if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")
if hasattr(sys.stderr, "reconfigure"):
    sys.stderr.reconfigure(encoding="utf-8")

CATALOGER_VERSION = "1.7.0"
OKHP3_HOMEPAGE    = "https://overkillhill.com"
OKHP3_GITHUB      = "https://github.com/OKHP3"

START_MARKER = "<!-- SKILLS_CATALOG_START -->"
END_MARKER   = "<!-- SKILLS_CATALOG_END -->"
WARN_COMMENT = ("<!-- ⚠️ DO NOT EDIT THIS SECTION MANUALLY"
                " — regenerated by scripts/gen-skills-readme.py -->")

FAMILY_SUMMARY_START   = "<!-- FAMILY_SUMMARY_START -->"
FAMILY_SUMMARY_END     = "<!-- FAMILY_SUMMARY_END -->"
FAMILY_INVENTORY_START = "<!-- FAMILY_INVENTORY_START -->"
FAMILY_INVENTORY_END   = "<!-- FAMILY_INVENTORY_END -->"

FAMILIES_TABLE_START = "<!-- FAMILIES_TABLE_START -->"
FAMILIES_TABLE_END   = "<!-- FAMILIES_TABLE_END -->"


def display_timestamp(value: datetime) -> str:
    """Format a human timestamp without POSIX-only %-d directives."""
    return f"{value.strftime('%B')} {value.day}, {value.strftime('%Y at %H:%M UTC')}"

# Directories excluded from root scan in --full mode
FULL_SKIP = frozenset({
    ".git", ".github", ".agents", ".claude", ".vscode",
    "skills",
    "node_modules", "__pycache__", ".venv", "venv",
    "dist", "build", "coverage", ".nyc_output", "attached_assets",
    "docs",
})


# ── Custom YAML frontmatter parser (no external dependencies) ─────────────────

def _strip_quotes(value: str) -> str:
    if len(value) >= 2 and value[0] == value[-1] and value[0] in ('"', "'"):
        return value[1:-1]
    return value


def parse_frontmatter(filepath: Path) -> dict:
    try:
        text = filepath.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError):
        return {}

    match = re.match(r"^---\n(.*?)\n---", text, re.DOTALL)
    if not match:
        return {}

    raw = match.group(1)
    result: dict = {}
    current_key: str | None = None
    current_block: list[str] = []
    in_block = False
    nested_key: str | None = None
    nested_dict: dict = {}
    in_nested = False

    for line in raw.splitlines():
        if in_block:
            if line.startswith("  ") or line.strip() == "":
                current_block.append(line.strip())
                continue
            result[current_key] = " ".join(current_block).strip()
            current_block, in_block = [], False

        if in_nested and line.startswith("  "):
            sub = re.match(r"  ([^:]+):\s*(.*)", line)
            if sub:
                nested_dict[sub.group(1).strip()] = _strip_quotes(sub.group(2).strip())
            continue
        if in_nested and not line.startswith("  "):
            result[nested_key] = nested_dict
            nested_dict, nested_key, in_nested = {}, None, False

        kv = re.match(r"^([^:]+):\s*(.*)", line)
        if not kv:
            continue
        key, value = kv.group(1).strip(), kv.group(2).strip()

        if value in ("|", ">"):
            current_key, in_block = key, True
        elif value == "":
            nested_key, in_nested = key, True
        else:
            result[key] = _strip_quotes(value)

    if in_block and current_block:
        result[current_key] = " ".join(current_block).strip()
    if in_nested and nested_dict:
        result[nested_key] = nested_dict

    return result


# ── Mode auto-detection ───────────────────────────────────────────────────────

def detect_mode(skills_dir: Path) -> str:
    """
    Inspect the first non-hidden subdirectory of skills_dir.
    If it contains SKILL.md directly: project mode (flat layout).
    If it contains subdirectories instead: library mode (categorized layout).
    """
    for d in sorted(skills_dir.iterdir()):
        if d.is_dir() and not d.name.startswith("."):
            return "project" if (d / "SKILL.md").exists() else "library"
    return "project"


# ── Skill discovery ───────────────────────────────────────────────────────────

def _record(skill_dir: Path, skill_md: Path, fm: dict, category: str, base: Path) -> dict:
    meta        = fm.get("metadata", {})
    if not isinstance(meta, dict):
        meta = {}
    name        = fm.get("name", skill_dir.name)
    raw_desc    = fm.get("description", "")
    description = re.sub(r"\s+", " ", raw_desc).strip()
    if len(description) > 100:
        description = description[:97] + "..."
    return {
        "name":          name,
        "dir_name":      skill_dir.name,
        "description":   description,
        "version":       meta.get("version", "—"),
        "category":      category,
        "origin":        meta.get("origin", "—"),
        "path":          str(skill_md.relative_to(base)),
        "name_mismatch": name != skill_dir.name,
    }


def discover_skills(skills_dir: Path, mode: str, base: Path | None = None) -> list[dict]:
    """Discover skills under skills_dir in the given mode.
    base: path used for relative link generation (defaults to skills_dir).
    """
    if base is None:
        base = skills_dir
    skills = []
    if mode == "library":
        for cat_dir in sorted(skills_dir.iterdir()):
            if not cat_dir.is_dir() or cat_dir.name.startswith("."):
                continue
            if cat_dir.name in FULL_SKIP:
                continue
            for skill_dir in sorted(cat_dir.iterdir()):
                if not skill_dir.is_dir():
                    continue
                md = skill_dir / "SKILL.md"
                if md.exists():
                    fm = parse_frontmatter(md)
                    skills.append(_record(skill_dir, md, fm, cat_dir.name, base))
    else:
        for skill_dir in sorted(skills_dir.iterdir()):
            if not skill_dir.is_dir() or skill_dir.name.startswith("."):
                continue
            md = skill_dir / "SKILL.md"
            if md.exists():
                fm   = parse_frontmatter(md)
                meta = fm.get("metadata", {})
                cat  = (meta.get("category", "—") if isinstance(meta, dict) else "—")
                skills.append(_record(skill_dir, md, fm, cat, base))
    return skills


def discover_full(root: Path) -> list[dict]:
    """
    Scan root-level family folders for the distribution surface.
    Skips FULL_SKIP directories and any folder without skill subdirectories.
    Always uses library mode (family/skill/SKILL.md).
    """
    skills = []
    for cat_dir in sorted(root.iterdir()):
        if not cat_dir.is_dir():
            continue
        if cat_dir.name in FULL_SKIP or cat_dir.name.startswith("."):
            continue
        for skill_dir in sorted(cat_dir.iterdir()):
            if not skill_dir.is_dir():
                continue
            md = skill_dir / "SKILL.md"
            if md.exists():
                fm = parse_frontmatter(md)
                skills.append(_record(skill_dir, md, fm, cat_dir.name, root))
    return skills


# ── FAMILY.md generation ──────────────────────────────────────────────────────

def extract_family_summary(family_dir: Path, skills: list[dict]) -> str:
    """
    Extract a one-paragraph summary for a family directory.

    Priority:
      1. First substantive paragraph from family_dir/README.md (strips headings,
         tables, HR lines, HTML comments, code fences, and pure status markers).
      2. Aggregated from child skill descriptions when README.md is absent.

    No external dependencies — pure stdlib string processing only.
    """
    readme = family_dir / "README.md"
    if readme.exists():
        try:
            text = readme.read_text(encoding="utf-8")
        except (OSError, UnicodeDecodeError):
            text = ""

        # Strip YAML frontmatter
        text = re.sub(r"^---\n.*?\n---\n?", "", text, flags=re.DOTALL)

        for block in re.split(r"\n{2,}", text):
            block = block.strip()
            if not block:
                continue
            # Skip structural elements
            if (block.startswith("#")
                    or block.startswith("|")
                    or block.startswith("<!--")
                    or block.startswith("```")
                    or block == "---"):
                continue
            # Skip pure status/placeholder lines (e.g. "**Status: placeholder.**")
            bare = re.sub(r"\*{1,3}", "", block).strip()
            if bare.lower().startswith("status:"):
                continue
            # Strip markdown links [text](url) → text
            block = re.sub(r"\[([^\]]+)\]\([^)]*\)", r"\1", block)
            # Strip bold/italic markers
            block = re.sub(r"\*{1,3}([^*\n]+)\*{1,3}", r"\1", block)
            # Collapse internal whitespace
            block = re.sub(r"[ \t]+", " ", block).strip()
            if len(block) > 20:
                return block[:500]

    # Fallback: aggregate from child skill descriptions
    n = len(skills)
    sw = "skill" if n == 1 else "skills"
    if not skills:
        return f"A family of {n} {sw}. No skills cataloged yet."
    descs = [
        s["description"] for s in skills
        if s["description"] and s["description"] != "—"
    ]
    if not descs:
        return f"A family of {n} {sw}."
    lead = descs[0].rstrip(".")
    return f"A family of {n} {sw}. {lead}."


def _extract_readme_bio(readme_path: Path) -> str:
    """
    Read a family README.md and return its content stripped of the leading
    heading line, ready to embed as the bio section of FAMILY.md.
    """
    try:
        text = readme_path.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError):
        return ""
    # Strip the first heading line (# Title / # Title/)
    text = re.sub(r"^#[^\n]*\n", "", text, count=1)
    return text.strip()


def _build_family_inventory(skills: list[dict], now_disp: str) -> str:
    """Build the auto-regenerated inventory table block (inside markers)."""
    n  = len(skills)
    sw = "skill" if n == 1 else "skills"
    rows = [
        f"*{n} {sw} &nbsp;·&nbsp; inventory last updated: **{now_disp}***",
        "",
        "| Skill | Description | Version |",
        "|---|---|---|",
    ]
    for s in sorted(skills, key=lambda x: x["name"]):
        flag = "⚠️ " if s["name_mismatch"] else ""
        link = f"[{s['name']}]({s['dir_name'].replace(chr(92), '/')}/SKILL.md)"
        rows.append(f"| {flag}{link} | {s['description']} | {s['version']} |")
    return "\n".join(rows)


def write_family_md(
    family_dir: Path,
    skills: list[dict],
    quiet: bool = False,
    dry_run: bool = False,
    absorb_readme: bool = True,
) -> bool:
    """
    Write or update FAMILY.md in family_dir.

    Structure:
      ---frontmatter---
      # family_name

      [bio section — free-form, absorbed from README.md on first creation,
       preserved on all subsequent runs]

      <!-- FAMILY_SUMMARY_START -->
      [auto-sourced summary, preserved if user edits]
      <!-- FAMILY_SUMMARY_END -->

      ## Skills (N)

      <!-- FAMILY_INVENTORY_START -->
      [always regenerated]
      <!-- FAMILY_INVENTORY_END -->

    On first creation:
      - Bio is populated from README.md (heading stripped), if present.
      - README.md is deleted after successful write (unless absorb_readme=False).

    On subsequent runs:
      - Bio is preserved exactly as-is.
      - Summary between markers is preserved if user has edited it.
      - Inventory is always regenerated.
      - README.md is never touched again.

    Returns True if the file was created or changed.
    """
    family_md  = family_dir / "FAMILY.md"
    readme_path = family_dir / "README.md"
    existed    = family_md.exists()

    now      = datetime.now(timezone.utc)
    now_iso  = now.strftime("%Y-%m-%dT%H:%M:%SZ")
    now_disp = display_timestamp(now)
    n        = len(skills)

    bio     = ""
    summary = extract_family_summary(family_dir, skills)
    display_name: str | None = None

    absorb_this_run = False

    if existed:
        try:
            existing_text = family_md.read_text(encoding="utf-8")
        except (OSError, UnicodeDecodeError):
            existing_text = ""

        # Preserve display_name from existing frontmatter so user-set
        # capitalisation overrides are never silently dropped on regeneration.
        existing_fm = parse_frontmatter(family_md)
        if "display_name" in existing_fm:
            display_name = existing_fm["display_name"]

        # Preserve bio: everything between the title line and FAMILY_SUMMARY_START
        title_m = re.search(r"^# .+\n", existing_text, re.MULTILINE)
        if title_m:
            after_title = existing_text[title_m.end():]
            if FAMILY_SUMMARY_START in after_title:
                bio = after_title[:after_title.find(FAMILY_SUMMARY_START)].strip()
            else:
                bio = after_title.strip()

        # If bio is still empty and a README.md is present, absorb it now
        if not bio and readme_path.exists() and absorb_readme:
            bio = _extract_readme_bio(readme_path)
            absorb_this_run = True

        # Preserve summary if user has edited it
        if FAMILY_SUMMARY_START in existing_text and FAMILY_SUMMARY_END in existing_text:
            s_idx = existing_text.find(FAMILY_SUMMARY_START) + len(FAMILY_SUMMARY_START)
            e_idx = existing_text.find(FAMILY_SUMMARY_END)
            preserved = existing_text[s_idx:e_idx].strip()
            if preserved:
                summary = preserved

    else:
        # First creation: absorb README.md as bio
        if readme_path.exists() and absorb_readme:
            bio = _extract_readme_bio(readme_path)
            absorb_this_run = True

    inventory_block = _build_family_inventory(skills, now_disp)
    name = family_dir.name

    bio_section = f"\n{bio}\n\n" if bio else "\n"
    display_name_line = f"display_name: {display_name}\n" if display_name else ""
    new_content = (
        f"---\n"
        f"family: {name}\n"
        f"{display_name_line}"
        f"skill_count: {n}\n"
        f"generated_by: okhp3-skill-cataloger v{CATALOGER_VERSION}\n"
        f"generated_at: {now_iso}\n"
        f"---\n"
        f"\n"
        f"# {name}\n"
        f"{bio_section}"
        f"{FAMILY_SUMMARY_START}\n"
        f"{summary}\n"
        f"{FAMILY_SUMMARY_END}\n"
        f"\n"
        f"## Skills ({n})\n"
        f"\n"
        f"{FAMILY_INVENTORY_START}\n"
        f"{inventory_block}\n"
        f"{FAMILY_INVENTORY_END}\n"
    )

    # Check if already current (ignoring timestamp line)
    if existed and not dry_run:
        try:
            old = family_md.read_text(encoding="utf-8")

            def _strip_ts(s: str) -> str:
                return re.sub(r"generated_at: .*", "generated_at: __TS__", s)

            if _strip_ts(new_content) == _strip_ts(old):
                if not quiet:
                    print(f"  — Unchanged: {family_md}")
                return False
        except (OSError, UnicodeDecodeError):
            pass

    if dry_run:
        verb = "update" if existed else "create"
        print(f"  [DRY RUN] Would {verb}: {family_md}")
        if not existed and readme_path.exists() and absorb_readme:
            print(f"  [DRY RUN] Would absorb and delete: {readme_path}")
        return True

    family_md.write_text(new_content, encoding="utf-8")
    verb = "Updated" if existed else "Created"
    if not quiet:
        print(f"  ✓ {verb}: {family_md}")

    # Absorb: delete README.md after successful write if we absorbed it this run
    if absorb_this_run and readme_path.exists():
        readme_path.unlink()
        if not quiet:
            print(f"  ✓ Absorbed and removed: {readme_path}")

    return True


# ── Families table (root README.md) ──────────────────────────────────────────

def discover_all_families(root: Path, skills: list[dict]) -> list[dict]:
    """
    Return a list of family summary dicts for ALL eligible root-level
    directories, including those with zero skills (placeholders).
    Ordered alphabetically.
    """
    skills_by_family: dict[str, list[dict]] = {}
    for s in skills:
        skills_by_family.setdefault(s["category"], []).append(s)

    families = []
    for d in sorted(root.iterdir()):
        if not d.is_dir():
            continue
        if d.name in FULL_SKIP or d.name.startswith("."):
            continue

        family_skills = skills_by_family.get(d.name, [])
        n = len(family_skills)

        # Prefer summary from FAMILY.md summary block; fall back to extract
        summary = ""
        fmd = d / "FAMILY.md"
        if fmd.exists():
            try:
                fmd_text = fmd.read_text(encoding="utf-8")
                if FAMILY_SUMMARY_START in fmd_text and FAMILY_SUMMARY_END in fmd_text:
                    s_idx = fmd_text.find(FAMILY_SUMMARY_START) + len(FAMILY_SUMMARY_START)
                    e_idx = fmd_text.find(FAMILY_SUMMARY_END)
                    summary = fmd_text[s_idx:e_idx].strip()
            except (OSError, UnicodeDecodeError):
                pass
        if not summary:
            summary = extract_family_summary(d, family_skills)
        if len(summary) > 90:
            summary = summary[:87] + "..."

        # Link target
        if fmd.exists():
            link = f"{d.name}/FAMILY.md"
        elif (d / "README.md").exists():
            link = f"{d.name}/README.md"
        else:
            link = f"{d.name}/"

        families.append({
            "name":           d.name,
            "skill_count":    n,
            "summary":        summary,
            "link":           link,
            "is_placeholder": n == 0,
        })

    return families


def build_families_table(families: list[dict], now_disp: str) -> str:
    """Build the auto-generated families table block."""
    now_iso   = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    n_active  = sum(1 for f in families if not f["is_placeholder"])
    n_total   = len(families)

    lines = [
        FAMILIES_TABLE_START,
        f"<!-- Generated: {now_iso} | Families: {n_total} ({n_active} active) -->",
        "",
        f"*{n_total} families &nbsp;·&nbsp; {n_active} active"
        f" &nbsp;·&nbsp; updated: **{now_disp}***",
        "",
        "| Family | Skills | What it covers |",
        "|---|---|---|",
    ]

    for f in families:
        name_cell  = f"[`{f['name']}/`]({f['link']})"
        count_cell = str(f["skill_count"]) if not f["is_placeholder"] else "— placeholder"
        lines.append(f"| {name_cell} | {count_cell} | {f['summary']} |")

    lines.append(FAMILIES_TABLE_END)
    return "\n".join(lines)


def inject_families_table(readme: Path, block: str) -> tuple[bool, str]:
    """
    Inject the families table block into README.md between FAMILIES_TABLE markers.
    Returns (changed, new_content). If markers are absent, returns (False, original).
    """
    if not readme.exists():
        return False, ""
    try:
        content = readme.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError):
        return False, ""

    if FAMILIES_TABLE_START not in content or FAMILIES_TABLE_END not in content:
        return False, content

    s = content.find(FAMILIES_TABLE_START)
    e = content.find(FAMILIES_TABLE_END) + len(FAMILIES_TABLE_END)
    new = content[:s] + block + content[e:]
    return new != content, new


# ── Validation ────────────────────────────────────────────────────────────────

def validate(skills: list[dict]) -> tuple[list[str], list[str]]:
    """Returns (fatal_errors, warnings). Fatals block generation; warnings do not."""
    errors:   list[str] = []
    warnings: list[str] = []
    seen: dict[str, str] = {}

    for s in skills:
        if s["name_mismatch"]:
            errors.append(
                f"  ✗ [{s['dir_name']}] frontmatter name '{s['name']}' "
                f"!= directory name '{s['dir_name']}'"
            )
        if s["name"] in seen:
            errors.append(
                f"  ✗ Duplicate name '{s['name']}' in '{s['dir_name']}' "
                f"and '{seen[s['name']]}'"
            )
        else:
            seen[s["name"]] = s["dir_name"]
        if not s["description"] or s["description"] == "—":
            errors.append(f"  ✗ [{s['name']}] no description in frontmatter")
        if s["version"] == "—":
            warnings.append(f"  ⚠ [{s['name']}] no version in metadata")

    return errors, warnings


# ── Table / section generation ────────────────────────────────────────────────

def _project_table(skills: list[dict]) -> str:
    if not skills:
        return "_No skills installed yet._"
    rows = [
        "| Skill | Description | Version | Category |",
        "|---|---|---|---|",
    ]
    for s in sorted(skills, key=lambda x: x["name"]):
        flag = " ⚠️" if s["name_mismatch"] else ""
        link = f"[{s['name']}]({s['path'].replace(chr(92), '/')})"
        rows.append(f"| {link}{flag} | {s['description']} | {s['version']} | {s['category']} |")
    return "\n".join(rows)


def _library_sections(skills: list[dict]) -> str:
    if not skills:
        return "_No skills in the library yet._"
    cats: dict[str, list[dict]] = {}
    for s in skills:
        cats.setdefault(s["category"], []).append(s)
    parts = []
    for cat in sorted(cats):
        items = sorted(cats[cat], key=lambda x: x["name"])
        sw = "skill" if len(items) == 1 else "skills"
        parts += [
            f"### {cat} ({len(items)} {sw})", "",
            "| Skill | Description | Version |",
            "|---|---|---|",
        ] + [
            f"| {'⚠️ ' if s['name_mismatch'] else ''}"
            f"[{s['name']}]({s['path'].replace(chr(92), '/')}) "
            f"| {s['description']} | {s['version']} |"
            for s in items
        ] + [""]
    return "\n".join(parts)


def build_block(skills: list[dict], mode: str, full: bool = False) -> str:
    now      = datetime.now(timezone.utc)
    now_iso  = now.strftime("%Y-%m-%d %H:%M UTC")
    now_disp = display_timestamp(now)
    n        = len(skills)
    sw       = "skill" if n == 1 else "skills"
    cats     = len({s["category"] for s in skills})
    surface  = "distribution" if full else "project-skills"

    lines = [START_MARKER, WARN_COMMENT]

    if mode == "library":
        lines.append(
            f"<!-- Generated: {now_iso} | Skills: {n} | Categories: {cats}"
            f" | Mode: library | Surface: {surface} -->"
        )
        lines += [
            "",
            f"*Catalog last updated: **{now_disp}** &nbsp;·&nbsp; "
            f"**{n}** {sw} across **{cats}** categories*",
            "",
            _library_sections(skills),
        ]
    else:
        lines.append(
            f"<!-- Generated: {now_iso} | Skills: {n} | Mode: project | Surface: {surface} -->"
        )
        lines += [
            "",
            f"*Catalog last updated: **{now_disp}** &nbsp;·&nbsp; **{n}** {sw} indexed*",
            "",
            _project_table(skills),
            "",
        ]

    lines.append(END_MARKER)
    return "\n".join(lines)


# ── README injection ──────────────────────────────────────────────────────────

def inject_strict(readme: Path, block: str) -> tuple[bool, str]:
    """
    Catalog mode injection: requires README to exist with markers in place.
    Errors hard on missing file or missing markers.
    """
    if not readme.exists():
        raise FileNotFoundError(
            f"README not found: {readme}\n"
            f"Create it with {START_MARKER} and {END_MARKER} markers first."
        )
    content = readme.read_text(encoding="utf-8")
    s = content.find(START_MARKER)
    e = content.find(END_MARKER)
    if s == -1 or e == -1:
        raise ValueError(
            f"Catalog markers not found in {readme}.\n"
            f"The README must contain:\n"
            f"  {START_MARKER}\n"
            f"  {END_MARKER}"
        )
    new = (content[:s] + block + "\n" + content[e + len(END_MARKER):]).rstrip() + "\n"
    return new != content, new


def inject_soft(output: Path, block: str) -> tuple[bool, str]:
    """
    Full index mode injection: creates output file if not present.
    If markers exist, replaces between them. Otherwise appends.
    """
    original = output.read_text(encoding="utf-8") if output.exists() else ""
    if START_MARKER in original and END_MARKER in original:
        s = original.find(START_MARKER)
        e = original.find(END_MARKER)
        new = (original[:s] + block + "\n" + original[e + len(END_MARKER):]).rstrip() + "\n"
    else:
        new = ((original.rstrip() + "\n\n" if original.strip() else "") + block).rstrip() + "\n"
    return new != original, new


# ── Catalog meta JSON ─────────────────────────────────────────────────────────

def write_catalog_meta(target_dir: Path, n: int, mode: str,
                       repo: str, surface: str) -> None:
    now_iso = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    meta = {
        "last_indexed": now_iso,
        "skill_count":  n,
        "mode":         mode,
        "surface":      surface,
        "indexed_by":   f"okhp3-skill-cataloger v{CATALOGER_VERSION}",
        "repo":         repo,
        "homepage":     OKHP3_HOMEPAGE,
        "github":       OKHP3_GITHUB,
    }
    (target_dir / ".catalog-meta.json").write_text(
        json.dumps(meta, indent=2) + "\n", encoding="utf-8"
    )


# ── Entry point ───────────────────────────────────────────────────────────────

def main() -> int:
    p = argparse.ArgumentParser(
        description=(
            f"okhp3-skill-cataloger v{CATALOGER_VERSION} "
            "— catalog or index Agent Skills"
        ),
        epilog=f"OverKill Hill P³ · {OKHP3_HOMEPAGE} · {OKHP3_GITHUB}",
    )
    p.add_argument(
        "--full", action="store_true",
        help=(
            "Full index mode: scan root-level family folders → README.md "
            "and write FAMILY.md in each family directory. "
            "Use in distribution repos (skillz). "
            "Default mode scans .agents/skills/ → .agents/skills/README.md."
        ),
    )
    p.add_argument(
        "--no-family-md", action="store_true",
        help="Skip FAMILY.md generation during --full mode.",
    )
    p.add_argument(
        "--no-absorb-readme", action="store_true",
        help=(
            "Skip absorbing and deleting family README.md files during --full. "
            "By default, when FAMILY.md is created for the first time, any "
            "README.md in the same directory is absorbed as the bio section "
            "and then deleted."
        ),
    )
    p.add_argument(
        "--skills-dir", default=".agents/skills",
        help="Path to skills root directory for catalog mode (default: .agents/skills)",
    )
    p.add_argument(
        "--output", default=None,
        help=(
            "Override output file path. "
            "Default: .agents/skills/README.md (catalog) or README.md (--full)."
        ),
    )
    p.add_argument(
        "--mode", choices=["auto", "project", "library"], default="auto",
        help="Catalog mode: auto (default), project (flat), library (categorized)",
    )
    p.add_argument(
        "--repo-name", default=Path.cwd().name,
        help="Repo name for .catalog-meta.json (default: current directory name)",
    )
    p.add_argument("--check",   action="store_true", help="Validate only — do not write files")
    p.add_argument("--json",    action="store_true", help="Print skill list as JSON to stdout")
    p.add_argument("--dry-run", action="store_true", help="Preview changes without writing files")
    p.add_argument("--quiet",   action="store_true", help="Suppress output unless errors/changes")
    args = p.parse_args()

    # ── Resolve paths ────────────────────────────────────────────────────────
    if args.full:
        scan_root  = Path(".")
        output     = Path(args.output) if args.output else Path("README.md")
        meta_dir   = Path(".")
        surface    = "distribution"
        forced_lib = True
    else:
        scan_root  = Path(args.skills_dir)
        output     = Path(args.output) if args.output else scan_root / "README.md"
        meta_dir   = scan_root
        surface    = "project-skills"
        forced_lib = False

    if not scan_root.exists():
        print(f"✗ Not found: {scan_root}", file=sys.stderr)
        return 1

    # ── Mode ─────────────────────────────────────────────────────────────────
    if forced_lib or args.mode == "library":
        effective_mode = "library"
        mode_label     = "library" if not forced_lib else "library (--full)"
    elif args.mode == "project":
        effective_mode = "project"
        mode_label     = "project"
    else:
        effective_mode = detect_mode(scan_root)
        mode_label     = f"auto → {effective_mode}"

    if not args.quiet and not args.json:
        tag = "[full index]" if args.full else "[catalog]"
        print(f"okhp3-skill-cataloger v{CATALOGER_VERSION} {tag} · mode: {mode_label}")

    # ── Discover ─────────────────────────────────────────────────────────────
    if args.full:
        skills = discover_full(scan_root)
    else:
        skills = discover_skills(scan_root, effective_mode)

    if not args.quiet and not args.json:
        print(f"Found {len(skills)} skill(s) in {scan_root}")

    if args.json:
        print(json.dumps(skills, indent=2))
        return 0

    # ── Validate ─────────────────────────────────────────────────────────────
    errors, warnings = validate(skills)
    if warnings and not args.quiet:
        print("\nWarnings:")
        for w in warnings:
            print(w)
    if errors:
        print("\nValidation errors:", file=sys.stderr)
        for e in errors:
            print(e, file=sys.stderr)
        print("\n✗ Fix errors before generating.", file=sys.stderr)
        return 1

    if args.check:
        if not args.full and output.exists():
            c = output.read_text(encoding="utf-8")
            if START_MARKER not in c or END_MARKER not in c:
                print("✗ README missing catalog markers.", file=sys.stderr)
                return 1
        print("✓ Check passed.")
        return 0

    # ── Build catalog block ───────────────────────────────────────────────────
    block = build_block(skills, effective_mode, full=args.full)

    # ── Dry run ──────────────────────────────────────────────────────────────
    if args.dry_run:
        if args.full:
            exists = output.exists()
            print(f"[DRY RUN] Would write to: {output}"
                  + (" (create)" if not exists else " (update)"))
            if not args.no_family_md:
                families_map: dict[str, list[dict]] = {}
                for s in skills:
                    families_map.setdefault(s["category"], []).append(s)
                family_names = sorted(families_map)
                absorb = not args.no_absorb_readme
                print(f"[DRY RUN] Would write FAMILY.md for "
                      f"{len(family_names)} family/families:")
                for fname in family_names:
                    fdir = scan_root / fname
                    existed = (fdir / "FAMILY.md").exists()
                    verb = "update" if existed else "create"
                    print(f"  [DRY RUN] Would {verb}: {fdir / 'FAMILY.md'}")
                    if not existed and (fdir / "README.md").exists() and absorb:
                        print(f"  [DRY RUN] Would absorb and delete: {fdir / 'README.md'}")
        else:
            try:
                changed, _ = inject_strict(output, block)
                print(f"[DRY RUN] Would {'update' if changed else 'leave unchanged'}: {output}")
            except (FileNotFoundError, ValueError) as exc:
                print(f"✗ {exc}", file=sys.stderr)
                return 1
        print(f"[DRY RUN] {len(skills)} skill(s) · mode: {effective_mode}")
        print(f"\n[DRY RUN] Block preview:\n\n{block}")
        return 0

    # ── Write catalog README ──────────────────────────────────────────────────
    try:
        if args.full:
            changed, new_content = inject_soft(output, block)
        else:
            changed, new_content = inject_strict(output, block)
    except (FileNotFoundError, ValueError) as exc:
        print(f"✗ {exc}", file=sys.stderr)
        return 1

    if changed:
        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_text(new_content, encoding="utf-8")
        if not args.quiet:
            print(f"✓ Updated: {output}")
    else:
        if not args.quiet:
            print("✓ Already current — no changes written.")

    # ── Write FAMILY.md for each discovered family ────────────────────────────
    if args.full and not args.no_family_md:
        families_map = {}
        for s in skills:
            families_map.setdefault(s["category"], []).append(s)

        if not args.quiet:
            n_fam = len(families_map)
            fw = "family" if n_fam == 1 else "families"
            print(f"\nWriting FAMILY.md for {n_fam} {fw}...")

        for family_name in sorted(families_map):
            family_dir = scan_root / family_name
            write_family_md(
                family_dir,
                families_map[family_name],
                quiet=args.quiet,
                dry_run=False,
                absorb_readme=not args.no_absorb_readme,
            )

    # ── Write Families table into root README.md ──────────────────────────────
    if args.full:
        families_list = discover_all_families(scan_root, skills)
        now_disp = display_timestamp(datetime.now(timezone.utc))
        fam_block = build_families_table(families_list, now_disp)
        fam_changed, fam_content = inject_families_table(output, fam_block)
        if fam_changed:
            output.write_text(fam_content, encoding="utf-8")
            if not args.quiet:
                print(f"✓ Updated Families table: {output}")
        elif FAMILIES_TABLE_START not in (output.read_text(encoding="utf-8") if output.exists() else ""):
            if not args.quiet:
                print(f"  ℹ Families table: add {FAMILIES_TABLE_START} / "
                      f"{FAMILIES_TABLE_END} markers to {output} to enable.")

    # ── Write catalog meta ────────────────────────────────────────────────────
    write_catalog_meta(meta_dir, len(skills), effective_mode, args.repo_name, surface)
    if not args.quiet:
        print(f"\n✓ Written: {meta_dir / '.catalog-meta.json'}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
