// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/tf-brand/PrintedMatter.tsx": () => import("../components/mockups/tf-brand/PrintedMatter.tsx"),
  "./components/mockups/tf-brand/ScriptoriumTheme.tsx": () => import("../components/mockups/tf-brand/ScriptoriumTheme.tsx"),
  "./components/mockups/tf-brand/SignalNoise.tsx": () => import("../components/mockups/tf-brand/SignalNoise.tsx")
};
