// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/telling-forward/AuthorHomeA.tsx": () => import("../components/mockups/telling-forward/AuthorHomeA.tsx"),
  "./components/mockups/telling-forward/AuthorHomeB.tsx": () => import("../components/mockups/telling-forward/AuthorHomeB.tsx"),
  "./components/mockups/telling-forward/ConceptBoardA.tsx": () => import("../components/mockups/telling-forward/ConceptBoardA.tsx"),
  "./components/mockups/telling-forward/ConceptBoardB.tsx": () => import("../components/mockups/telling-forward/ConceptBoardB.tsx"),
  "./components/mockups/telling-forward/ReaderEntryA.tsx": () => import("../components/mockups/telling-forward/ReaderEntryA.tsx"),
  "./components/mockups/telling-forward/ReaderEntryB.tsx": () => import("../components/mockups/telling-forward/ReaderEntryB.tsx"),
  "./components/mockups/tf-brand/CivicArchive.tsx": () => import("../components/mockups/tf-brand/CivicArchive.tsx"),
  "./components/mockups/tf-brand/PrintedMatter.tsx": () => import("../components/mockups/tf-brand/PrintedMatter.tsx"),
  "./components/mockups/tf-brand/ScriptoriumTheme.tsx": () => import("../components/mockups/tf-brand/ScriptoriumTheme.tsx"),
  "./components/mockups/tf-brand/SignalNoise.tsx": () => import("../components/mockups/tf-brand/SignalNoise.tsx"),
  "./components/mockups/mobile-approach/ThreadAtlas.tsx": () => import("../components/mockups/mobile-approach/ThreadAtlas.tsx")
};
